# Generated by Django 3.1.5 on 2021-04-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210411_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.product')),
                ('optional_price', models.PositiveIntegerField(verbose_name='Цена большой пиццы')),
            ],
            bases=('main_app.product',),
        ),
    ]
