# Generated by Django 3.2 on 2021-05-03 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210424_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сумма заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='time_begin',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 15, 1, 3, 761423), verbose_name='Время поступления заказа'),
        ),
    ]
