# Generated by Django 3.2 on 2021-05-03 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210503_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_begin',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 15, 26, 46, 930490), verbose_name='Время поступления заказа'),
        ),
    ]
