# Generated by Django 3.2 on 2021-05-09 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_order_time_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_begin',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 17, 55, 21, 675031), verbose_name='Время поступления заказа'),
        ),
    ]
