# Generated by Django 3.2 on 2021-05-09 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_order_time_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_begin',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 18, 17, 29, 957408), verbose_name='Время поступления заказа'),
        ),
    ]
